export const slotData = {data:[
        {
          id: 1,
          name: "John Doe",
          stickiness: "high",
          percentageStickiness: "85%",
          attendanceRate: "90%",
          avgTimeSpent: "45 mins",
          attendance30: "70%",
          attendanceCount: 10,
          correctness: "80%",
          improvement: "High",
        },
        {
          id: 2,
          name: "Jane Smith",
          stickiness: "medium",
          percentageStickiness: "75%",
          attendanceRate: "88%",
          avgTimeSpent: "40 mins",
          attendance30: "60%",
          attendanceCount: 8,
          correctness: "70%",
          improvement: "Medium",
        },
        {
          id: 3,
          name: "Sam Brown",
          stickiness: "low",
          percentageStickiness: "65%",
          attendanceRate: "80%",
          avgTimeSpent: "35 mins",
          attendance30: "50%",
          attendanceCount: 7,
          correctness: "60%",
          improvement: "Low",
        },
        {
          id: 4,
          name: "Audy",
          stickiness: "high",
          percentageStickiness: "90%",
          attendanceRate: "95%",
          avgTimeSpent: "50 mins",
          attendance30: "80%",
          attendanceCount: 12,
          correctness: "85%",
          improvement: "Very High",
        },
        {
          id: 5,
          name: "Charlie White",
          stickiness: "medium",
          percentageStickiness: "78%",
          attendanceRate: "85%",
          avgTimeSpent: "42 mins",
          attendance30: "65%",
          attendanceCount: 9,
          correctness: "72%",
          improvement: "Medium",
        },
      ]};